#! /bin/sh
# https://wiki.archlinux.org/index.php/Bspwm

python $HOME/.config/bspwm/bspwmrc.py 2> /tmp/bspwm_log &

# TODO: Move the rest into a python script

. $HOME/.config/bspwm/panel_settings

# mkfifo $PANEL_FIFO
#
# bspc control --subscribe > "$PANEL_FIFO" &
# xtitle -sf "T%s"         > "$PANEL_FIFO" &

X_RES=$(python ./utils.py)
export PANEL_WIDTH=$(echo "$X_RES / 2 - 5" | bc)
export PANEL_OFFSET=$(echo "$X_RES / 2" | bc)

$HOME/.config/bspwm/left_panel.sh &
$HOME/.config/bspwm/right_panel.sh &

COMP_REG=$(echo "$X_RES - 10" | bc)

compton -G --shadow-exclude-reg ${COMP_REG}x18+5+0 --config \
    ~/.config/compton/compton.conf &
