#! /bin/sh
# https://wiki.archlinux.org/index.php/Bspwm

python $HOME/.config/bspwm/bspwmrc.py 2> /tmp/bspwm_log &

X_RES=$(python $HOME/.config/bspwm/utils.py)

COMP_REG=$(echo "$X_RES - 10" | bc)

compton -G --shadow-exclude-reg ${COMP_REG}x18+5+0 --config \
    ~/.config/compton/compton.conf &
